<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<AssemblyName>AnyDoingOnAnyDay</AssemblyName>
		<RootNamespace>AnyDoingOnAnyDay</RootNamespace>
		<LangVersion>latest</LangVersion>
		<Nullable>disable</Nullable>
		
		<!-- Не копируем зависимости в выходную папку -->
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		
		<!-- BepInEx -->
		<DefineConstants>$(DefineConstants);BIE_API_V5</DefineConstants>
	</PropertyGroup>
	
	<PropertyGroup>
		<!-- Game Path -->
		<GameDir>F:\GAMES\Graveyard Keeper 2</GameDir>
		<!-- Managed Path -->
		<ManagedDir>$(GameDir)\GraveyardKeeper2_Data\Managed</ManagedDir>
		<!-- МО2 Instance Path -->
		<MO2ModsDir>F:\_Game Profiles_\Graveyard Keeper 2\mods</MO2ModsDir>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Localization\en.json" />
		<None Remove="Localization\ko.json" />
		<None Remove="Localization\ru.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Localization\en.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Localization\ko.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Localization\ru.json">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
	<ItemGroup>
		<!-- BepInEx -->
		<Reference Include="BepInEx">
			<HintPath>$(GameDir)\BepInEx\core\BepInEx.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="0Harmony">
			<HintPath>$(GameDir)\BepInEx\core\0Harmony.dll</HintPath>
			<Private>false</Private>
		</Reference>
		
		<!-- Game assemblies -->
		<Reference Include="Assembly-CSharp">
			<HintPath>$(ManagedDir)\Assembly-CSharp.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="FlowCanvas">
		  <HintPath>$(ManagedDir)\FlowCanvas.dll</HintPath>
		</Reference>
		<Reference Include="LazyBearTechnology">
			<HintPath>$(ManagedDir)\LazyBearTechnology.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="ParadoxNotion">
		  <HintPath>$(ManagedDir)\ParadoxNotion.dll</HintPath>
		</Reference>
		<Reference Include="ParadoxNotion">
			<HintPath>$(ManagedDir)\ParadoxNotion.dll</HintPath>
		</Reference>
		<Reference Include="Rewired_Core">
			<HintPath>$(ManagedDir)\Rewired_Core.dll</HintPath>
		</Reference>
		<Reference Include="Sirenix.Serialization">
		  <HintPath>$(ManagedDir)\Sirenix.Serialization.dll</HintPath>
		</Reference>
		
		<!-- Unity -->
		<Reference Include="UnityEngine">
			<HintPath>$(ManagedDir)\UnityEngine.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(ManagedDir)\UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
		  <HintPath>$(ManagedDir)\UnityEngine.IMGUIModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.PhysicsModule">
		  <HintPath>$(ManagedDir)\UnityEngine.PhysicsModule.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI">
		  <HintPath>$(ManagedDir)\UnityEngine.UI.dll</HintPath>
		</Reference>
	</ItemGroup>
	
	<!-- Автоматическое копирование скомпилированного файла мода в плагины игры -->
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<PropertyGroup>
			<!-- 1. Расставляем пробелы перед заглавными буквами в очищенном имени (AnyDoingOnAnyDay -> Any Doing on Any Day) -->
			<ModFolderName>$([System.Text.RegularExpressions.Regex]::Replace($(AssemblyName), '(\B[A-Z])', ' $1'))</ModFolderName>

			<!-- 2. Формируем правильные пути для деплоя -->
			<TargetModPath>$(MO2ModsDir)\$(ModFolderName)\plugins\$(AssemblyName)</TargetModPath>
		</PropertyGroup>

		<!-- Копируем саму .dll текущего проекта в plugins -->
		<Copy SourceFiles="$(OutputPath)$(AssemblyName).dll" DestinationFolder="$(TargetModPath)" SkipUnchangedFiles="true" />

		<!-- Копируем чистые JSON для автономного SimpleLocalizer -->
		<Copy SourceFiles="@(Content)" Condition="'%(Extension)' == '.json'" DestinationFolder="$(TargetModPath)\Localization" SkipUnchangedFiles="true" />
	</Target>
</Project>